# The Major.Minor version of PHP
ARG PHP_VERSION

# The suffix of the Docker image to be appended to PHP_VERSION
# Example: "-rc" for php:8.6-rc-cli
ARG PHP_VERSION_DOCKERSUFFIX=""

FROM php:${PHP_VERSION}${PHP_VERSION_DOCKERSUFFIX}-cli

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

COPY imagine-utilities /usr/local/bin/

COPY --chmod=0777 imagine-install /usr/local/bin/

COPY --chmod=0777 imagine-fix-apt /usr/local/bin/
